pipeline {
    agent { node { label 'maven' } }
    options { skipDefaultCheckout true }
    stages {
        stage('Checkout') {
            steps {
                sendNotification('started', 'team@example.com')
                git branch: 'notifiction', url: 'https://github.com/suchan-redhat/DO400-apps'
            } 
        }

        stage('Test') {
            steps {
                dir('simple-calculator') {
                    sh './mvnw clean test'
                } 
            }
        } 
    }
    post {
        always {
            sendNotification('finished', 'team@example.com')
        }
    }
}



void sendNotification(String action, String email) {
    mail to: "${email}",
        subject: "Pipeline ${action}: ${currentBuild.fullDisplayName}",
        body: "The following pipeline ${action}: ${env.BUILD_URL}"
}
